name: com
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  firebase_auth:
  cloud_firestore:
  google_sign_in:
  flutter_facebook_login:
  font_awesome_flutter:

  pedometer: ^1.2.0
  sensors:
  syncfusion_flutter_charts: ^18.1.53
  percent_indicator:
  flutter_launcher_icons:

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/step.png"

flutter:

  uses-material-design: true

  assets:
    - images/
    - images/basic-logo.png
    - images/logo.png
    - images/main_pattern.jpg
    - images/npat.jpg
    - images/OP-screen_background.jpg
    - images/stairs.jpg
    - images/Icons/
    - images/Icons/Cycling.png
    - images/Icons/Jogging.png
    - images/Icons/pull-ups.png
    - images/Icons/push-ups.png
    - images/Icons/Sit-Ups.png
    - images/Icons/steps.png
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Girassol
      fonts:
        - asset: fonts/Girassol-Regular.ttf
    - family: PTSerif
      fonts:
        - asset: fonts/PTSerif-Regular.ttf
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf